### ISSUE TITLE
Unhandled exception PG::Error

### ISSUE THREAD

**Issue by thbar** [sportngin/okcomputer#154]
When using the ActiveRecord check with Rails 5.2.2 and pg 1.0.0, the database check (https://github.com/sportngin/okcomputer/blob/master/lib/ok_computer/built_in_checks/active_record_check.rb) will raise a PG::Error, instead of providing a clean "failed" output, if the database is shutdown.

I'm not 100% exactly sure yet why this is happening. `PG::Error` inherits from `StandardError` if I read well, so the `rescue` should work.

That said a reconnection by AR is happening, and may explain that.

Here is the full stack trace:

```
Started GET "/health-checks/all" for ::1 at 2019-01-25 18:44:28 +0100
  
PG::Error (could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
):
  
activerecord (5.2.2) lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `set_client_encoding'
activerecord (5.2.2) lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `configure_connection'
activerecord (5.2.2) lib/active_record/connection_adapters/postgresql_adapter.rb:266:in `block in reconnect!'
/Users/thbar/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.2.2) lib/active_record/connection_adapters/postgresql_adapter.rb:263:in `reconnect!'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract_adapter.rb:435:in `verify!'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:860:in `block in checkout_and_verify'
activesupport (5.2.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport (5.2.2) lib/active_support/callbacks.rb:816:in `_run_checkout_callbacks'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:859:in `checkout_and_verify'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
activerecord (5.2.2) lib/active_record/connection_handling.rb:118:in `retrieve_connection'
activerecord (5.2.2) lib/active_record/connection_handling.rb:90:in `connection'
activerecord (5.2.2) lib/active_record/migration.rb:554:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rollbar (2.16.2) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
rollbar (2.16.2) lib/rollbar.rb:146:in `scoped'
rollbar (2.16.2) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
rollbar (2.16.2) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
rack (2.0.6) lib/rack/handler/webrick.rb:86:in `service'
/Users/thbar/.rbenv/versions/2.5.3/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/Users/thbar/.rbenv/versions/2.5.3/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/Users/thbar/.rbenv/versions/2.5.3/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by anfleene** [comment]
Since OkComputer isn't in the stack trace, I assume this is rails barfing before it even hands it off to the check. Seeing `activerecord (5.2.2) lib/active_record/migration.rb` in the stack trace looks to be the "Check Pending Migration" code that rails runs when it loads the environment. 

That check is for testing connection drops, it won't work with rails environments that haven't booted yet.
